export enum ActionType {
  SET_EDIT_STATE,
  SET_VIEW_STATE,
  SET_PREVIEW_STATE,
  SET_CLICKED_CL_STATE,
  SET_CLICKED_RESUME_STATE,
  SET_RESUME_PERSONAL_STATEMENT_STATE,
  SET_RESUME_TITLE_STATE,
  SET_RESUME_NAME_STATE,
  SET_RESUME_EMAIL_STATE,
  SET_RESUME_MOBILE_STATE,
  SET_RESUME_VISA_STATE,
  SET_RESUME_LOCATION_STATE,
}
